services:
  project498.webapi:
    image: project498.webapi
    build:
      context: .
      dockerfile: Project498.WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=project498;Username=postgres;Password=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: project498
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

